# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2004"
  config.vm.define "buildsys-patterns-collection"
  config.vm.box_url = "Vagrantfile"
  config.vm.provider "virtualbox" do |v|
  	v.name = "patterns-collection"
  	v.memory = 4096
  	v.cpus = 2
  end

  config.vm.provision :shell, path: "provision.sh"

end
